Implement form handleing
v3xlabs/edit-ens-page pull request #1
Opened 2023-11-22 20:55 UTC by svemat01

2023-11-23 22:31 UTC, svemat01 commented
Current TODO:
- Rework chains
- Ability to add more fields
- Make better graphics for indicating modified field

2023-12-11 19:53 UTC, lucemans requested changes

2023-12-11 19:53 UTC, lucemans commented on web/package.json
>  }
```suggestion
        "typescript": "^5.3.2"
    }
}

```

2023-12-11 19:54 UTC, lucemans approved these changes
LGTM

2023-12-11 19:54 UTC, merged